---

# Ansible Requirements for SSH Hardening Role
# Install with: ansible-galaxy install -r requirements.yml
# Collections
collections:
  - name: ansible.posix
    version: ">=1.3.0"
  - name: community.general
    version: ">=4.0.0"

# Roles
roles:
  - name: iamenr0s.ansible_role_pkg_management
  - name: iamenr0s.ansible_role_firewalld
  - name: iamenr0s.ansible-role-kernel-configuration